staging workflow

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -1,4 +1,5 @@
 name: 'Vprofile IAC'
+
 on:
   push:
     branches:
@@ -11,11 +12,10 @@ on:
       - main
     paths:
       - terraform/**
+
 env:
-  # Credentials for deployment on AWS
-  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_SECRET_KEY_ID }}
-  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_ID }}
-  # S3 bucket for the terraform state
+  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
   BUCKET_TF_STATE: ${{ secrets.BUCKET_TF_STATE }}
   AWS_REGION: us-east-2
   EKS_CLUSTER: vprofile-eks
@@ -35,12 +35,15 @@ jobs:
 
       - name: Setup Terraform with specified version on the runner
         uses: hashicorp/setup-terraform@v2
-        #with:
-        #  terraform_version: 1.6.3
+        with:
+          terraform_version: 1.6.3
 
       - name: Terraform init
         id: init
-        run: terraform init -backend-config="bucket=${BUCKET_TF_STATE}"
+        run: terraform init \
+          -backend-config="bucket=${BUCKET_TF_STATE}" \
+          -backend-config="key=terraform.tfstate" \
+          -backend-config="region=${AWS_REGION}"
 
       - name: Terraform format
         id: fmt
@@ -56,5 +59,5 @@ jobs:
         continue-on-error: true
 
       - name: Terraform plan status
-        if: steps.plan.outcome == 'failure'
-        run: exit 1 && echo "Terraform plan failed. Please check the configuration."
+        if: steps.plan.conclusion == 'failure'
+        run: echo "Terraform plan failed. Please check the configuration." && exit 1
